### ISSUE TITLE
List value returned by graph query should be deserialized.

### ISSUE THREAD

**Issue by garyhai** [tompro/redis_graph#12]
```rust
    let query = "RETURN [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] AS list";
    let client = redis::Client::open("redis://127.0.0.1/").unwrap();
    let mut con = client.get_connection().unwrap();
    let res: GraphResultSet = con.graph_query("test-graph", query).unwrap();
    let r = &res.data[0];
    let list: Vec<usize> = r.get_scalar("list").unwrap_or_default();
    dbg!(list);
```

output: []
expected: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**Comment by tompro** [comment]
Running this query returns me a redis string ‘[0,1,2,3,4,5,6,7,8,9]'. Do you have any docs that indicate that this should map to another redis type?

**Comment by tompro** [comment]
Found the syntax in the docs as follows:

> Arrays
> When array values are specified in a RETURN clause, the representation in the response is the array string representation. This is done solely for better readability of the response. The string representation of an array which contains graph entities, will print only their ID. A node string representation is round braces around its ID, and edge string representation is brackets around the edge ID.

So the string rep. seems to be fine for now and arrays in RETURN clause are sort of a toString call anyhow. You can get your expected output by receiving the returned string rep. and the parse the result. Keep in mind that if done with a list of nodes it will only contain their ids and no data.
```
let list: String = r.get_scalar("list").unwrap();
```

**Comment by garyhai** [comment]
Thank you very much for your response. I was wondering if it would be possible to add a method to `GraphResult` specifically for converting list-type strings to their corresponding arrays. For example: `pub fn get_list<T: FromRedisValue>(&self, key: &str) -> Option<Vec<T>>`. My quick and dirty solution for my personal project is:

```rust
fn get_list<'a, T>(s: &str) -> Result<Vec<T>>
 where
 T: Deserialize<'a>,
{
serde_json::from_str::<Vec<T>>(s).map_err(Into::into)
}
```
